class Constants:

    EMAIL_ID = 'EMAIL_ID'
    GEMINI_BASE_URL = 'https://generativelanguage.googleapis.com/v1beta/openai/'
    GEMINI_MODEL_LITE = 'gemini-2.5-flash-lite-preview-06-17'
    GEMINI_MODEL_MEDIUM = 'gemini-2.5-flash'
    GOOGLE_API_KEY = 'GOOGLE_API_KEY'
    OPEN_AI_CONTENT = 'content'
    OPEN_AI_ROLE = 'role'
    OPEN_AI_SYSTEM = 'system'
    OPEN_AI_TOOL_CALL = 'tool_calls'
    OPEN_AI_USER = 'user'
    PUSHOVER_TOKEN = 'PUSHOVER_TOKEN'
    PUSHOVER_URL = 'https://api.pushover.net/1/messages.json'
    PUSHOVER_USER = 'PUSHOVER_USER'
    SENDGRID_API_KEY = 'SENDGRID_API_KEY'
